[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#4CAF7B"
backgroundColor="#FFFFFF00"
secondaryBackgroundColor="#FFFFFF"
textColor="#1A1F25"
font="sans serif"
